version: "3"

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: foo-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: foo-kafka
    depends_on:
      - zookeeper
    env_file:
      - ../env/.env
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
